myapp/__init__.py
from flask import Flask
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
import time
from myapp.function.disk_io import DiskIO
from myapp.config import file_path, root, secret_key

diskio = DiskIO(file_path, root)
# 记录服务器启动时间戳
SERVER_START_TIMESTAMP = str(int(time.time()))
# 记录已经轮播的目录
blacklisted_directories = set()


db = SQLAlchemy()
def create_app():
    # 初始化 Flask 应用
    app = Flask(__name__)
    app.secret_key = secret_key
    app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 60 * 60 * 24 * 7  # 缓存一周
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///user.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    # 初始化数据库
    db.init_app(app)
    return app

# 用户模型
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(150), nullable=False)

    @classmethod
    def get(cls, username):
        return cls.query.filter_by(username=username).first()

myapp/app.py
from flask import jsonify, make_response
import time
from flask_login import LoginManager
from werkzeug.exceptions import BadRequest
from werkzeug.security import generate_password_hash
from myapp.config import init_username, init_password
from myapp import create_app, db, User
from myapp.function.basic import app_logger

app = create_app()
# 初始化数据库，创建初始账户
with app.app_context():
    db.create_all()
    # 加密密码
    hashed_password = generate_password_hash(init_password)
    # 检查用户是否已经存在，避免重复插入
    if not User.query.filter_by(username=init_username).first():
        initial_user = User(username=init_username, password=hashed_password)
        db.session.add(initial_user)
        db.session.commit()
        app_logger.debug(f"User '{init_username}' created with hashed password.")
    else:
        app_logger.debug(f"User '{init_username}' already exists.")

# 配置图片的缓存控制头
@app.after_request
def add_cache_control_headers(response):
    """
    在每个响应返回给客户端之前，向图片响应添加缓存控制头。
    该函数作为 Flask 的请求后处理钩子函数 (after_request)，
    目的是为了优化图片资源的缓存管理。

    参数:
    response (Response): Flask 的响应对象。
    返回:
    Response: 修改后的响应对象。
    """
    if response.mimetype.startswith('image'):
        # 设置Cache-Control头，图片资源公开缓存，有效期为一年，并且表示资源是不可变的
        response.headers['Cache-Control'] = 'public, max-age=31536000, immutable'
        # 设置Expires头，为当前时间加上一年的秒数
        response.headers['Expires'] = int(time.time()) + 31536000
        # 设置ETag头，用于资源的缓存校验，避免不必要的下载
        response.headers['ETag'] = response.get_etag()[0]
    return response

# 设置 Flask-Login
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login.login'
# 用户加载函数
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# 异常处理
@app.errorhandler(BadRequest)
def handle_bad_request(e):
    response = jsonify({"error": "Bad Request", "message": str(e)})
    return make_response(response, 400)

# 登录蓝图
from myapp.function.login import login_blueprint
app.register_blueprint(login_blueprint)

# 主页蓝图
from myapp.function.index import index_blueprint
app.register_blueprint(index_blueprint)

# 图片查看页面
from myapp.function.image_viewer import image_viewer_blueprint
app.register_blueprint(image_viewer_blueprint)

# 设置界面
from myapp.function.little_blueprint import index_button_blueprint,delete_blueprint
app.register_blueprint(index_button_blueprint)

# 删除功能
app.register_blueprint(delete_blueprint)


if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True)

myapp/function/little_blueprint.py
from flask import Blueprint, render_template, redirect, request, jsonify
from flask_login import login_required
import urllib.parse
from myapp import diskio

index_button_blueprint = Blueprint('index_button', __name__)
@index_button_blueprint.route('/settings')
@login_required
def settings():
    return render_template('settings.html')


@index_button_blueprint.route('/random')
@login_required
def random():
    random_path = diskio.random_dir()
    # 对 random_path 进行 URL 编码
    encoded_random_path = urllib.parse.quote(random_path)
    return redirect(f'/{random_path}')


delete_blueprint = Blueprint('delete_blueprint', __name__)
@delete_blueprint.route('/delete', methods=['POST'])
@login_required
def delete():
    """
    删除路由，处理删除图像和删除目录的请求
    :return: JSON 格式的响应结果
    """
    data = request.get_json()
    if 'path' not in data:
        return jsonify(success=False, message='路径不存在'), 400
    path_relative_root = data['path']
    success = diskio.delete_item(path_relative_root)
    return jsonify(success=success)

myapp/templates/image_viewer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ folder_name }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/image_viewer.css', v=timestamp) }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
    <div class="image-container" id="imageContainer">
        <img src="" alt="Left Image" class="image" id="leftImage">
        <div class="image-container">
            <img src="" alt="Current Image" class="image" id="currentImage">
            <div class="message visible" id="Message">消息文本</div>
            <div class="option-bar hidden" id="optionBar">
                <div class="top-bar-left">
                    <div class="filename" id="filename"></div>
                </div>
                <div class="top-bar-right" id="topBarRight">
                    <button class="top-bar-button delete" id="deleteButton">🗑</button>
                    <button class="top-bar-button sub-option" id="subOptionButton">⋮</button>
                    <button class="top-bar-button carouse" id="carouselButton">▶</button>
                </div>
            </div>
        </div>
        <img src="" alt="Right Image" class="image" id="rightImage">
    </div>
    <script nonce="{{ nonce }}"> // 将模板变量的值注入全局变量
        const imagesJson = {{ images_json|tojson|safe}};
        let folderName = "{{ folder_name }}"
        let currentImageIndex = {{ current_image_index }};
        let carousingFromServer = {{ carousing|default('false', true) | tojson }};
        const carousing = carousingFromServer === true;
        let CarouselFps = "{{ carousel_fps }}";
        console.log('carousing=',carousing, ';CarouselFps=', CarouselFps)
    </script>
    <script src="{{ url_for('static', filename='js/image_viewer.js', v=timestamp) }}"></script>
</body>
</html>

myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>images</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css', v=timestamp) }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
    <div class="container">
        <div class="sub-container">
        {% for index in range(0, items|length) %}
        <div class="item">

                {% if items[index]['preview_image'] %}
                    <a href="{{ url_for('index.index', url_path=items[index]['path'])}}?from_viewer={{from_viewer}}&v={{timestamp}}">
                    <div class="placeholder hidden" data-aspect-ratio="{{ items[index]['preview_image']['aspect_ratio'] }}"></div>
                    <img data-src="{{ url_for('index.index', url_path=items[index]['preview_image']['path'] ~ '?v=' ~ timestamp) }}" alt="预览图片" class="lazy">
                    <p class="text-folder hidden">{{ items[index]['name']|default('No Name Provided') }}</p></a>
                {% else %}
                    {% if items[index]['is_pic'] %}
                        {% if from_viewer %}
                            <a href="{{ url_for('image_viewer.image_viewer', image_path=items[index]['path'] ~ '?v=' ~ timestamp) }}"
                               onclick="event.preventDefault(); navigateTo(this.href);">
                                <div class="placeholder hidden" data-aspect-ratio="{{ items[index]['aspect_ratio'] }}"></div>
                                <img data-src="{{ url_for('index.index', url_path=items[index]['path'] ~ '?v=' ~ timestamp) }}" alt="预览图片" class="lazy">
                                <p class="text-pic hidden">{{ items[index]['name'] }}</p>
                            </a>
                        {% else %}
                            <a href="{{ url_for('image_viewer.image_viewer', image_path=items[index]['path'] ~ '?v=' ~ timestamp) }}">
                                <div class="placeholder hidden" data-aspect-ratio="{{ items[index]['aspect_ratio'] }}"></div>
                                <img data-src="{{ url_for('index.index', url_path=items[index]['path'] ~ '?v=' ~ timestamp) }}" alt="预览图片" class="lazy">
                                <p class="text-pic hidden">{{ items[index]['name'] }}</p>
                            </a>
                        {% endif %}
                    {% endif %}
                {% endif %}
        </div>
        {% endfor %}
        </div>
        <div class="sub-container">
        </div>
        <div class="sub-container">
        </div>
    </div>
    <a href="{{ url_for('index_button.settings') }}" class="settings-button">
        ⚙️
    </a>
    <a href="{{ url_for('index_button.random', url_path='random')}}" class="random-button">
        ✨
    </a>
    <script>
        const items = {{ items|tojson|safe }};
    </script>
    <script src="{{ url_for('static', filename='js/scripts.js', v=timestamp) }}"></script>
</body>
</html>

myapp/templates/login.html
<!-- templates/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css', v=timestamp) }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
    <div class="login-container">
        <h2>Login</h2>
        <form method="POST">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" required autocomplete="username">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" name="password" id="password" required autocomplete="current-password">
            </div>
            <button type="submit" class="btn">Login</button>
        </form>
    </div>
</body>
</html>

myapp/templates/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Settings</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/settings.css', v=timestamp) }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
    <div class="header">
        <a href="#" class="back-button">返回</a>
        <a href="{{ url_for('login.logout') }}" class="logout-button">注销</a>
    </div>
    <div class="content">
        <h1>帮助文档</h1>
        <p>浏览页面左滑返回上一目录</p>
        <p>图片查看页面点击文件名返回浏览图片所在文件夹</p>

        <div class="comments-section">
            <div class="column comments-list">
                <ul>
                    {% for comment in comments[:(comments|length)] %}
                        <li data-comment-id="{{ comment.id }}">
                            <span>{{ comment.text | safe }}</span>
                            <button class="delete-button">删除</button>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="column comment-form">
                <h2>评论</h2>
                <form action="{{ url_for('settings.settings') }}" method="post">
                    <textarea name="comment" required></textarea>
                    <button type="submit">提交</button>
                </form>
            </div>
        </div>
    </div>

<script src="{{ url_for('static', filename='js/settings.js', v=timestamp) }}"></script>

</body>
</html>